import { HeadLine, LayoutContainer, ContactList } from "@/components";
import { useGetContacts, usePostContact } from "@/hooks";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Content Flow App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <LayoutContainer>
        <HeadLine />
        <ContactList />
      </LayoutContainer>
    </>
  );
}
